#!/bin/bash

# Set the path of ATOM_HOME to be a folder in the current working directory with
# the name equal to "[the name of this script]-home".
# E.g. "atom-foo" will use a folder named "atom-foo-home".
thisScriptPath="$(readlink -f -- "$0")" # Full path to script
export ATOM_HOME="${thisScriptPath%.*}"-home

# Launch Atom with arguments (assumes the Atom launch files are in your PATH)
atom $@
